version: "3.5"

services:
  api:
    build: ./app
    # 개발시 사용한 이미지 -> 없으면 자동으로 빌드
    # image: server:0.2
    container_name: api
    ports:
      - "500:500"
    volumes:
      - type: bind
        source: ./app
        target: /code
    command: "500"

    networks:
      - payhere

  db:
    # build: ./DB
    # 개발시 사용한 이미지 -> 없으면 자동으로 빌드
    image: mysql:5.7
    container_name: db
    # platform: : linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: payhere
      MYSQL_DATABASE: payhere
      MYSQL_USER: payhere
      MYSQL_PASSWORD: payhere
    # dbeaver 사용을 위한 expose
    # expose:
    #   - "3306"
    # ports:
    #   - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: bind
        source: ./DB/data
        target: /var/lib/mysql

    networks:
      - payhere

networks:
  payhere:
    driver: bridge


