version: "3.5"

services:
  api:
    build: ./app
    image: server:0.2
    container_name: api
    ports:
      - "500:500"
    volumes:
      - type: bind
        source: ./app
        target: /code
    command: "500"

    networks:
      - server

  db:
    image: mysql:5.7
    container_name: db
    # platform: : linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: payhere
      MYSQL_DATABASE: payhere
      MYSQL_USER: payhere
      MYSQL_PASSWORD: payhere
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    
    volumes:
      - type: bind
        source: ./DB/data
        target: /var/lib/mysql

    networks:
      - server

networks:
  server:
    external: true



